DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS TEAM;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS ADVISOR;
DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS TEMPLATE;
DROP TABLE IF EXISTS CONTENT;

CREATE TABLE ADVISOR(
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL
);

CREATE TABLE CLIENT(
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  STATUS TEXT NOT NULL
);

CREATE TABLE TEAM(
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  COURSE TEXT,
  TB_GENERATED INT NOT NULL,
  ADVISOR_ID INT,
  CLIENT_ID INT,
  FOREIGN KEY (ADVISOR_ID) REFERENCES ADVISOR (ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID)
);

CREATE TABLE STUDENT(
  STUDENT_ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  EMAIL TEXT,
  TEAM_ID INT,
  FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID)
);

CREATE TABLE ADMIN(
  ID INTEGER PRIMARY KEY,
  USERNAME TEXT NOT NULL,
  HASH TEXT NOT NULL,
  SALT TEXT NOT NULL
);

CREATE TABLE TEMPLATE(
  ID INTEGER PRIMARY KEY,
  LOCATION TEXT NOT NULL,
  FOREIGN KEY (ID) REFERENCES CONTENT (ID)
);

CREATE TABLE CONTENT(
  ID INTEGER PRIMARY KEY,
  TITLE TEXT NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  COURSE TEXT NOT NULL,
  PAGE TEXT NOT NULL,
  IS_TEMPLATE INT NOT NULL,
  IS_EXTERNAL INT NOT NULL,
  IS_INTERNAL INT NOT NULL,
  HREF TEXT NOT NULL
);
